### PR TITLE
[MACRO-2831] - Remove [cmd + N] hotkeys from editor

### PR DESCRIPTION
**Pull request by danielkweon**
Notion Document: https://www.notion.so/macrocom/Macro-2831-Removing-all-cmd-N-hotkeys-in-the-Editor-3840985846224638aeea8fca35042401

- This PR removes the [cmd + N] hotkeys from the lok-wasm editor. The editor will NOT react when these hotkeys are pressed. 

- The [cmd + N] hotkeys are removed from all modules (TextDocument, Spreadsheet, FormDocument, etc...). If Macro decides to support these modules in the future, the assumption is that it will be in the web and not want these hotkeys. If we do, we can revert parts of this PR as needed.

### CODE REVIEW

**Review by synoet — APPROVED** [review]
lg

**Comment by chase** [comment]
Could probably get a way with just adding to the ignored hotkey shortcuts here, instead of requiring a rebuild here: https://github.com/coparse-inc/app-monorepo/blob/97d1326e535c2fb2539ef29859b029a2b07922a4/packages/editor/src/components/PlaceholderDocument.tsx#L70-L90

**Comment by danielkweon** [comment]
We probably could get away with removing them only from the app-monorepo. But if the functionality isnt needed, I think it's best to remove it from both for consistency and clean code.

**Comment by chase** [comment]
> We probably could get away with removing them only from the app-monorepo. But if the functionality isnt needed, I think it's best to remove it from both for consistency and clean code.

Mostly from a complexity perspective.
If you want to have these changes in monorepo, you'll have to build it locally and manually add the built .data and .metadata (not the fccache one) since CI hasn't been setup to build them, because there's no reliable way to only update it only when changes are made.

The other thing to consider is having to go back and resolve merge conflicts when we pull from upstream. This file is prone to those, so in general taking the least invasive action is usually easiest for us.

**Pull request merged**
