### PR TITLE
CHG pause painting scroll [MACRO-2209]

### PR DESCRIPTION
**Pull request by synoet**

### CODE REVIEW

**Comment by synoet** [comment]
NOT ready need to do some more testing

**Comment by synoet** [comment]
@chase Alright I did some more testing and I didn't notice any stalling related to re-introducing this change.
- Doesn't stall the initial paint.
- Scrolling Normally looks normal
- Scrolling quickly (holding the scroll bar and quickly dragging down) also doesn't stall

Tested this on a couple docs including flutter.

I was at some point able to get some painting issues but I don't think they where related to this change / happened in a nondeterministic fashion. 

If it turns out that this causes issues I can come back to it again. 

PS: i'm on a high DPI display idk if that affects anything?

**Comment by chase** [comment]
> @chase Alright I did some more testing and I didn't notice any stalling related to re-introducing this change.
> 
> * Doesn't stall the initial paint.
> * Scrolling Normally looks normal
> * Scrolling quickly (holding the scroll bar and quickly dragging down) also doesn't stall
> 
> Tested this on a couple docs including flutter.
> 
> I was at some point able to get some painting issues but I don't think they where related to this change / happened in a nondeterministic fashion.
> 
> If it turns out that this causes issues I can come back to it again.
> 
> PS: i'm on a high DPI display idk if that affects anything?

Could you describe the painting issues? If it is like duplicated tiles or glitchy looking, it's possible that the stop paint condition isn't right. But if it did the same thing before this, probably no reason to introduce it one way or another.

The non-deterministic fashion is probably a race condition. Don't burn time on it, but if it happens again, try to document roughly what you did to make it occur.

**Comment by synoet** [comment]
@chase I did some light testing again today. I don't think the issues im experiencing are related to these changes as I experienced them on main aswell.

Occasionally typing after scroll will cause some tiles to be incorrect... ie some tile ends up in the wrong place after making changes

**Comment by chase** [comment]
> @chase I did some light testing again today. I don't think the issues im experiencing are related to these changes as I experienced them on main aswell.

Alright. Then we can merge this.

> Occasionally typing after scroll will cause some tiles to be incorrect... ie some tile ends up in the wrong place after making changes

That's probably a high DPI bug then, looks like the sizing and positioning in your view is entirely wrong at least based on the screenshots I've seen.

**Review by chase — APPROVED** [review]

**Pull request merged**
